#!/usr/bin/env bash
#
# One-time server provisioning for the audit logging service.
#
# Installs PostgreSQL, creates the service user, database and role, writes the
# systemd EnvironmentFile, and enables the unit so it starts at boot. Safe to
# re-run: an existing /etc/audit/audit.env is never overwritten, so the database
# password survives repeat runs.
#
# Deploy the binary itself with ./deploy.sh afterwards.
#
# Usage: ./provision.sh <ssh-host>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APP_DIR="${APP_DIR:-/app/audit}"
ENV_DIR="${ENV_DIR:-/etc/audit}"
SERVICE_NAME="${SERVICE_NAME:-audit}"
SERVICE_USER="${SERVICE_USER:-audit}"
DB_NAME="${DB_NAME:-audit}"
DB_USER="${DB_USER:-audit}"
PORT="${PORT:-8090}"
BIND_ADDR="${BIND_ADDR:-127.0.0.1}"
SKIP_UFW="${SKIP_UFW:-0}"

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <ssh-host>" >&2
  echo "Example: $0 muni-demo" >&2
  exit 1
fi

REMOTE_HOST="$1"
LOCAL_SERVICE_FILE="$SCRIPT_DIR/$SERVICE_NAME.service"

if [[ ! -f "$LOCAL_SERVICE_FILE" ]]; then
  echo "Service file not found: $LOCAL_SERVICE_FILE" >&2
  exit 1
fi

echo "[1/2] Copying $SERVICE_NAME.service to $REMOTE_HOST"
scp -q "$LOCAL_SERVICE_FILE" "$REMOTE_HOST:/tmp/$SERVICE_NAME.service"

echo "[2/2] Provisioning $REMOTE_HOST"
ssh "$REMOTE_HOST" "sudo env \
  APP_DIR='$APP_DIR' \
  ENV_DIR='$ENV_DIR' \
  SERVICE_NAME='$SERVICE_NAME' \
  SERVICE_USER='$SERVICE_USER' \
  DB_NAME='$DB_NAME' \
  DB_USER='$DB_USER' \
  PORT='$PORT' \
  BIND_ADDR='$BIND_ADDR' \
  SKIP_UFW='$SKIP_UFW' \
  bash -s" <<'REMOTE'
set -euo pipefail

ENV_FILE="$ENV_DIR/audit.env"
UNIT_FILE="/etc/systemd/system/$SERVICE_NAME.service"

echo "--> Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq postgresql postgresql-contrib ufw curl openssl

echo "--> Ensuring service user: $SERVICE_USER"
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --no-create-home --home-dir "$APP_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
fi

echo "--> Ensuring directories"
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0755 "$APP_DIR"
install -d -o root -g "$SERVICE_USER" -m 0750 "$ENV_DIR"

echo "--> Ensuring PostgreSQL is running and enabled at boot"
systemctl enable --now postgresql

# An existing env file is the source of truth for the password. Only generate a
# new one when there is nothing to preserve.
DB_PASSWORD=""
if [[ -f "$ENV_FILE" ]] && grep -q '^DATABASE_URL=' "$ENV_FILE"; then
  echo "--> Keeping credentials in existing $ENV_FILE"
else
  DB_PASSWORD="$(openssl rand -hex 24)"
fi

role_exists="$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER'")"
if [[ "$role_exists" == "1" ]]; then
  if [[ -n "$DB_PASSWORD" ]]; then
    echo "--> Role $DB_USER exists but $ENV_FILE does not; resetting its password"
    sudo -u postgres psql -q -c "ALTER ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD'"
  fi
else
  if [[ -z "$DB_PASSWORD" ]]; then
    echo "$ENV_FILE holds a password but role $DB_USER does not exist." >&2
    echo "Remove $ENV_FILE and re-run to generate a fresh credential." >&2
    exit 1
  fi
  echo "--> Creating role $DB_USER"
  sudo -u postgres psql -q -c "CREATE ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD'"
fi

db_exists="$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'")"
if [[ "$db_exists" == "1" ]]; then
  echo "--> Database $DB_NAME already exists"
else
  # Owning the database gives the role CREATE/USAGE on schema public via
  # pg_database_owner on PostgreSQL 15+, so no extra grants are needed.
  echo "--> Creating database $DB_NAME owned by $DB_USER"
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
fi

if [[ -n "$DB_PASSWORD" ]]; then
  echo "--> Writing $ENV_FILE"
  umask 077
  cat > "$ENV_FILE" <<ENVFILE
# Generated by deployment/provision.sh. Contains a database credential.
STORAGE_BACKEND=postgres
DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@127.0.0.1:5432/$DB_NAME?sslmode=disable
BIND_ADDR=$BIND_ADDR
PORT=$PORT
MAX_PAYLOAD_BYTES=32768
ENVFILE
  chown root:"$SERVICE_USER" "$ENV_FILE"
  chmod 0640 "$ENV_FILE"
fi

echo "--> Installing $UNIT_FILE"
install -o root -g root -m 0644 "/tmp/$SERVICE_NAME.service" "$UNIT_FILE"
rm -f "/tmp/$SERVICE_NAME.service"
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"

if [[ "$SKIP_UFW" == "1" ]]; then
  echo "--> Skipping firewall configuration (SKIP_UFW=1)"
else
  echo "--> Configuring firewall (SSH allowed; $PORT stays closed)"
  ufw allow OpenSSH
  ufw --force enable
fi

echo
echo "Provisioning complete."
echo "  binary path : $APP_DIR/audit (not deployed yet)"
echo "  env file    : $ENV_FILE"
echo "  listening on: $BIND_ADDR:$PORT"
echo "  boot        : $SERVICE_NAME enabled"
echo
echo "Next: run ./deploy.sh <ssh-host> to build and install the binary."
REMOTE
